# Generated by Django 2.2.7 on 2019-11-28 14:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.'), ('Judge', 'Judge'), ('Professor', 'Professor')], default='', max_length=10)),
                ('name', models.CharField(max_length=181)),
                ('designation', models.CharField(blank=True, max_length=40, null=True)),
                ('phone_no', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)])),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('department', models.CharField(blank=True, max_length=40, null=True)),
                ('room_no', models.CharField(blank=True, max_length=40, null=True)),
                ('in_office', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_title', models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.'), ('Judge', 'Judge'), ('Professor', 'Professor')], default='', max_length=10)),
                ('visitor_name', models.CharField(blank=True, max_length=181)),
                ('visitor_phone_no', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)])),
                ('visitor_email', models.EmailField(max_length=70)),
                ('in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('out_time', models.DateTimeField(blank=True, null=True)),
                ('left_office', models.BooleanField(default=False)),
                ('verification', models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1111)])),
                ('host_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Employee')),
            ],
        ),
    ]
